'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const browser = fs.readFileSync(path.join(__dirname, 'browser-overlay.js'), 'utf8');
const popupName = fs.readFileSync(path.join(__dirname, 'riftbound-popup-name.js'), 'utf8');
const map = fs.readFileSync(path.join(__dirname, 'riftbound-spot-map-overlay.js'), 'utf8');
const css = fs.readFileSync(path.join(__dirname, 'riftbound-spot-map-overlay.css'), 'utf8');
const html = fs.readFileSync(path.join(__dirname, 'riftbound-spot-map-overlay.html'), 'utf8');
const main = fs.readFileSync(path.join(__dirname, '..', 'main.js'), 'utf8');
assert.match(browser, /bundleCaption/);
assert.match(popupName, /combo-visual/i);
assert.match(popupName, /VISUAL COMBO SPOT/);
assert.match(map, /const GRID_SPOTS = 4/);
assert.match(map, /const LANE_PAGE_INTERVAL_MS = 6000/);
assert.match(map, /pairedPrimaryGroups/);
assert.match(map, /isPairedCombo/);
assert.match(map, /pagesFor/);
assert.match(map, /renderPairedComboLane/);
assert.match(map, /combo-hero-plus/);
assert.doesNotMatch(map, /visibleColumns/);
assert.match(map, /page\.style\.gridTemplateColumns = `repeat\(\$\{gridSpots\}/);
assert.match(map, /while \(page\.length < gridSpots/);
assert.match(map, /lanes\[0\]\.style\.gridColumn = '2'/);
assert.doesNotMatch(map, /follow\.append\(leftList, gap, rightList\)/);
assert.match(map, /visualCardKey/);
assert.match(map, /takeUnseenCards/);
assert.match(map, /const consumed = new Set/);
assert.match(map, /takeUnseenCards/);
assert.doesNotMatch(map, /takeUnseenVisualNames|representativeCards/);
assert.match(map, /const sharedCards = takeUnseenCards/);
assert.match(map, /SIG \/ ON \/ AA \/ Epic \/ Rare/);
assert.match(map, /forcePaint/);
assert.match(map, /new Set\(\['champion', 'baron', 'poro', 'sp'\]\)/);
assert.match(css, /\.lane-page\s*\{[^}]*grid-template-columns:\s*repeat\(4/s);
assert.match(css, /\.combo-lane\s*\{[^}]*grid-column:\s*span 1/s);
assert.match(css, /\.combo-hero-row/);
assert.match(css, /\.combo-follow-grid/);
assert.match(css, /\.combo-hero-plus/);
assert.match(html, /riftbound-spot-map\.css\?v=305/);
assert.match(html, /riftbound-spot-map\.js\?v=305/);
assert.match(main, /bundleGroups:/);
assert.match(map, /imageWarmCache/);
assert.match(map, /warmPage/);
assert.match(main, /public, max-age=31536000, immutable/);
assert.match(main, /image_fallback_url/);
assert.match(map, /warmCardImage/);
assert.match(map, /fallbackUsed/);
assert.doesNotMatch(map, /breakLedger|buyer_name|active_break_board_cards|INSERT\s+INTO|UPDATE\s+active_break_board_cards/i);
console.log('combo overlay four-spot compact representative visual tests passed');
