const assert = require('assert');
const fs = require('fs');
const path = require('path');

const rendererRoot = __dirname;
const sourceRoot = path.resolve(rendererRoot, '..');
const appSource = fs.readFileSync(path.join(rendererRoot, 'app.js'), 'utf8');
const htmlSource = fs.readFileSync(path.join(rendererRoot, 'index.html'), 'utf8');
const cssSource = fs.readFileSync(path.join(rendererRoot, 'breaker-center.css'), 'utf8');
const preloadSource = fs.readFileSync(path.join(sourceRoot, 'preload.js'), 'utf8');
const mainSource = fs.readFileSync(path.join(sourceRoot, 'main.js'), 'utf8');
const overlayHtmlSource = fs.readFileSync(path.join(rendererRoot, 'riftbound-spot-map-overlay.html'), 'utf8');
const overlayCssSource = fs.readFileSync(path.join(rendererRoot, 'riftbound-spot-map-overlay.css'), 'utf8');
const overlayJsSource = fs.readFileSync(path.join(rendererRoot, 'riftbound-spot-map-overlay.js'), 'utf8');
const browserOverlaySource = fs.readFileSync(path.join(rendererRoot, 'browser-overlay.js'), 'utf8');

assert.match(htmlSource, /id="break-bag-mode"/);
assert.match(htmlSource, /Singles · exact positions/);
assert.match(preloadSource, /setBreakBoardMappingMode/);
assert.match(mainSource, /function buildRiftboundSinglesAudit/);
assert.match(mainSource, /spotType: 'RIFTBOUND_SINGLE'/);
assert.match(mainSource, /kind: 'riftbound-single'/);
assert.match(mainSource, /ensureVendettaBoardOne\(database\)/);
assert.match(mainSource, /ensureSpiritforgedExpandedBoardSix\(database\)/);
assert.match(mainSource, /ensureUnleashedExpandedBoardSeven\(database\)/);
assert.match(mainSource, /spotType: 'SPIRITFORGED_EXPANDED'/);
assert.match(mainSource, /buildSpiritforgedExpandedBreakAudit/);
assert.match(mainSource, /preview_title: 'SPIRITFORGED 50-SPOT'/);
assert.match(mainSource, /spotType: 'UNLEASHED_CASE_BREAK'/);
assert.match(mainSource, /buildUnleashedCaseBreakAudit/);
assert.match(mainSource, /preview_title: 'UNLEASHED 19-SPOT CASE'/);
assert.match(mainSource, /spotType: 'UNLEASHED_EXPANDED'/);
assert.match(mainSource, /buildUnleashedExpandedBreakAudit/);
assert.match(mainSource, /expandedMode: visual\.mode/);
assert.match(mainSource, /laneSymbol: visual\.laneSymbol/);
assert.match(mainSource, /preview_title: 'UNLEASHED 39-SPOT · BOARD 7'/);
assert.match(appSource, /Each purchased position shows only its exact single card/);
assert.match(appSource, /isUnleashedCaseBreak/);
assert.match(appSource, /isUnleashedExpanded/);
assert.match(appSource, /isUnleashedChampionSplit/);
assert.match(appSource, /unleashed-expanded-champion-panel/);
assert.match(appSource, /unleashed-card-symbol/);
assert.match(appSource, /💎/);
assert.match(appSource, /🔥/);
assert.match(appSource, /UNLEASHED 39-SPOT · BOARD 7/);
assert.match(appSource, /BARON \+ ALL SIX AA RUNES/);
assert.match(appSource, /AA Runes belong to Spot 13/);
assert.match(appSource, /function riftboundSinglesAuditGrid/);
assert.match(appSource, /isOriginsBundle \|\| isSpiritforgedBundle \|\| isVendettaBundle/);
assert.match(appSource, /vendetta-linear-family-grid/);
assert.match(appSource, /isVendettaBundle \|\| isUnleashedCaseBreak/);
assert.match(appSource, /unleashed-case-linear-family-grid/);
assert.match(cssSource, /\.vendetta-audit-panel \.vendetta-linear-family-grid/);
assert.match(cssSource, /\.unleashed-case-break-panel \.unleashed-case-linear-family-grid/);
assert.match(cssSource, /\.unleashed-card-symbol/);
assert.match(cssSource, /\.card-symbol-signature/);
assert.match(cssSource, /\.card-symbol-overnumbered/);
assert.match(cssSource, /\.card-symbol-alternate-art/);
assert.match(cssSource, /\.unleashed-expanded-champion-panel \.champion-audit-head/);
assert.match(cssSource, /\.riftbound-singles-grid\s*\{[^}]*grid-template-columns:\s*repeat\(5,/s);
assert.match(browserOverlaySource, /RIFTBOUND SINGLE · EXACT CARD/);
assert.match(browserOverlaySource, /imageMarkup\(bundleCards\[0\] \|\| card\)/);
assert.match(browserOverlaySource, /const displayCard = bundleCards\[0\] \|\| card/);
assert.match(browserOverlaySource, /displayCard\.image_url/);
assert.match(browserOverlaySource, /if \(revealOnly \|\| boardRevealActive\) processClaim\(payload\.claim \|\| null\)[\s\S]*const enabled = payload\.enabled === true/);
assert.doesNotMatch(browserOverlaySource, /function render\([^)]*claim/);
assert.match(mainSource, /claim: \(revealOnly \|\| boardReveal\) \? browserOverlayClaim\(cards\) : null/);
assert.match(mainSource, /build: app\.getVersion\(\)/);
assert.match(htmlSource, /Ten reusable boards/);
assert.match(htmlSource, /one of ten setup squares/);

assert.match(htmlSource, /id="copy-riftbound-spot-map-overlay"/);
assert.match(htmlSource, /id="toggle-riftbound-spot-map"/);
assert.doesNotMatch(htmlSource, /id="riftbound-spot-overview"/);
assert.doesNotMatch(htmlSource, /id="riftbound-spot-overview-toggle"/);
assert.doesNotMatch(htmlSource, /id="open-riftbound-spot-map-overlay"/);
assert.doesNotMatch(htmlSource, /Spot Map Overview/);
assert.doesNotMatch(preloadSource, /getRiftboundSpotOverview/);
assert.doesNotMatch(preloadSource, /openRiftboundSpotMapOverlay/);
assert.match(preloadSource, /copyRiftboundSpotMapOverlay/);
assert.match(preloadSource, /getRiftboundSpotMapStatus/);
assert.match(preloadSource, /setRiftboundSpotMapEnabled/);
assert.match(mainSource, /function listRiftboundSpotOverview\(\)/);
assert.match(mainSource, /function publicRiftboundSpotMap\(\)/);
assert.doesNotMatch(mainSource, /ipcMain\.handle\('breaker:riftbound-spot-overview'/);
assert.match(mainSource, /requestPath === '\/api\/riftbound-spot-map'/);
assert.match(mainSource, /let riftboundSpotMapEnabled = false/);
assert.match(mainSource, /entries: riftboundSpotMapEnabled \? publicRiftboundSpotMap\(\) : \[\]/);
assert.match(mainSource, /breaker:set-riftbound-spot-map-enabled/);
assert.match(mainSource, /riftboundSpotMapImageHydration\.clear\(\)/);
assert.match(mainSource, /requestPath === '\/riftbound-spot-map\.html'/);
assert.match(mainSource, /breaker:copy-riftbound-spot-map-overlay/);
assert.doesNotMatch(mainSource, /breaker:open-riftbound-spot-map-overlay/);
assert.match(mainSource, /riftboundSpotOverviewCacheKey/);
assert.match(mainSource, /public, max-age=31536000, immutable/);
assert.match(mainSource, /function resolveRiftboundSpotMapImagePath\(cardId\)/);
assert.match(mainSource, /riftbound-spot-image/);
assert.match(mainSource, /scheduleRiftboundSpotMapImageWarm/);
assert.match(mainSource, /image_fallback_url/);
assert.doesNotMatch(mainSource, /UPDATE cards SET image_path = \? WHERE id = \?/);
assert.match(mainSource, /api\/riftbound-spot-image\/\$\{cardId\}/);
assert.match(mainSource, /-400w\.webp/);
assert.match(mainSource, /lookupOpenRiftImage/);
assert.match(mainSource, /riftboundSpotMapImageHydration\.delete/);
assert.match(mainSource, /v=305/);
assert.doesNotMatch(appSource, /function renderRiftboundBreakerCenter\(\)\s*\{\s*renderPendingBreakRounds\(\);\s*renderRiftboundSpotOverview/);
assert.doesNotMatch(appSource, /getRiftboundSpotOverview/);
assert.match(overlayHtmlSource, /id="lane-stage"/);
assert.match(overlayHtmlSource, /id="lane-track"/);
assert.match(overlayCssSource, /grid-template-columns:\s*repeat\(4,\s*minmax\(0,\s*1fr\)\)/);
assert.match(overlayCssSource, /\.lane-page\.singles-page\s*\{[^}]*grid-template-columns:\s*repeat\(5,\s*minmax\(0,\s*1fr\)\)/s);
assert.doesNotMatch(overlayCssSource, /grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\)/);
assert.match(overlayCssSource, /\.mapped-list\s*\{\s*display:\s*grid/);
assert.doesNotMatch(overlayCssSource, /rotateY\(/);
assert.match(overlayJsSource, /const GRID_SPOTS = 4/);
assert.match(overlayJsSource, /const SINGLES_GRID_SPOTS = 5/);
assert.match(overlayJsSource, /entry\?\.spotType === 'RIFTBOUND_SINGLE'/);
assert.match(overlayJsSource, /const LANE_PAGE_INTERVAL_MS = 6000/);
assert.doesNotMatch(overlayJsSource, /const GRID_SPOTS = 3/);
assert.doesNotMatch(overlayJsSource, /const LANE_PAGE_INTERVAL_MS = 2000/);
assert.match(overlayJsSource, /while \(page\.length < gridSpots/);
assert.match(overlayJsSource, /lanes\[0\]\.style\.gridColumn = '2'/);
assert.match(overlayJsSource, /lanes\[1\]\.style\.gridColumn = '3'/);
assert.match(overlayJsSource, /state\.enabled \? REFRESH_INTERVAL_MS : 10000/);
assert.match(overlayJsSource, /imageWarmCache\.clear\(\)/);
assert.match(overlayJsSource, /OBS Spot Map is idle/);
assert.match(overlayJsSource, /familyFor\(entry/);
assert.match(overlayJsSource, /makeMappedList\(related\)/);
assert.match(mainSource, /linearOverlayProfileForPresetSlot\(activePresetSlot\)/);
assert.match(mainSource, /\.map\(card => applyLinearOverlayProfileToCard\(card, customLinearOverlayProfile\)\)/);
assert.match(mainSource, /linearOverlay:\s*Boolean\(linearOverlayProfileForEntry\(entry\)\)/);
assert.match(overlayJsSource, /const limit = entry\.linearOverlay \? 1 : 2/);
assert.doesNotMatch(overlayJsSource, /rotateFamilyCards/);
assert.match(overlayJsSource, /translateX\(-50%\)/);
assert.match(overlayJsSource, /imageWarmCache/);
assert.match(overlayJsSource, /warmPage/);
assert.match(overlayJsSource, /Attach error recovery before assigning src/);
assert.match(overlayJsSource, /forcePaint/);
assert.doesNotMatch(overlayJsSource, /takeUnseenVisualNames|representativeCards/);
assert.doesNotMatch(overlayJsSource, /preload\(entries\.flatMap\(entry => \[entry\.spotCard/);

assert.match(overlayJsSource, /renderPairedComboLane/);
assert.match(overlayCssSource, /\.combo-lane\s*\{[^}]*grid-column:\s*span 1/s);
console.log('Riftbound OBS-only Spot Map, four-card mapped/five-card Singles viewer, and visual-only paired-family checks passed.');
