'use strict';
const assert = require('assert');
const { auditComboMapping, VENDETTA_RIVAL_ON_CHAMPIONS, UNLEASHED_RUNE_CHAMPION_UNITS } = require('./RiftboundComboMappingAudit');
const audit = auditComboMapping();
assert.equal(VENDETTA_RIVAL_ON_CHAMPIONS.length, 22);
assert.equal(UNLEASHED_RUNE_CHAMPION_UNITS.flatMap(group => group.names).length, 12);
assert.equal(audit.spotCount, 17);
assert.equal(audit.championSpotCount, 11);
assert.equal(audit.poroSpotCount, 6);
assert.deepEqual(audit.missingUnleashedChampions, []);
assert.deepEqual(audit.missingVendettaSignatures, []);
assert.deepEqual(audit.missingVendettaRivalOns, []);
assert.deepEqual(audit.duplicateRivalOns, []);
assert.deepEqual(audit.missingPoros, []);
assert.equal(audit.missingBaron, false);
assert.deepEqual(audit.badStandaloneOnAssignments, []);
assert.deepEqual(audit.duplicateStandaloneOns, []);
assert.deepEqual(audit.badPoroVisualPairs, []);
assert.equal(audit.riftHeraldVisualDomain, 'Order');
assert.equal(audit.irresistibleVisualDomain, 'Body');
assert.equal(audit.standaloneOnAssignments.length, 11);
assert.equal(audit.ok, true);
console.log('UNL + VEN 17-spot combo mapping audit passed: all champion/ON/Poro/Baron families accounted for.');
