const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('breakSuite', {
  getOverview: (gameCode) => ipcRenderer.invoke('library:overview', gameCode),
  getCards: (filters) => ipcRenderer.invoke('library:cards', filters),
  getCatalogSets: () => ipcRenderer.invoke('library:sets'),
  getRarities: (gameCode, setCode) => ipcRenderer.invoke('library:rarities', gameCode, setCode),
  getCard: (id) => ipcRenderer.invoke('library:card', id),
  setSaved: (id, shouldSave) => ipcRenderer.invoke('library:set-saved', id, shouldSave),
  setClassification: (id, classification) => ipcRenderer.invoke('library:set-classification', id, classification),
  setRiftboundTreatment: (id, treatment) => ipcRenderer.invoke('library:set-riftbound-treatment', id, treatment),
  getBreakBoard: () => ipcRenderer.invoke('break:board-cards'),
  getActiveBreakBoard: () => ipcRenderer.invoke('break:active-board-cards'),
  getBreakBoardOverview: () => ipcRenderer.invoke('break:board-overview'),
  setBreakBoardGame: (gameCode) => ipcRenderer.invoke('break:set-game', gameCode),
  setBreakBoardMappingMode: (mappingMode) => ipcRenderer.invoke('break:set-mapping-mode', mappingMode),
  getBreakBoardPresets: () => ipcRenderer.invoke('break:list-presets'),
  saveBreakBoardPreset: (payload) => ipcRenderer.invoke('break:save-preset', payload),
  getBoardMappingEditor: (slot) => ipcRenderer.invoke('break:mapping-editor', slot),
  searchBoardMappingLibrary: (payload) => ipcRenderer.invoke('break:mapping-search', payload),
  saveBoardMapping: (payload) => ipcRenderer.invoke('break:save-mapping', payload),
  resetBoardMapping: (slot) => ipcRenderer.invoke('break:reset-mapping', slot),
  loadBreakBoardPreset: (slot) => ipcRenderer.invoke('break:load-preset', slot),
  clearBreakBoardPreset: (slot) => ipcRenderer.invoke('break:clear-preset', slot),
  setBreakBoardCard: (id, shouldShow) => ipcRenderer.invoke('break:set-card', id, shouldShow),
  clearBreakBoard: () => ipcRenderer.invoke('break:clear-board'),
  saveBreakBoard: (payload) => ipcRenderer.invoke('break:save-board', payload),
  getBreakBoardListingDescriptions: () => ipcRenderer.invoke('break:listing-descriptions'),
  saveBreakBoardListingDescription: (payload) => ipcRenderer.invoke('break:save-listing-description', payload),
  resetBreakBoardListingDescription: (gameCode) => ipcRenderer.invoke('break:reset-listing-description', gameCode),
  copyBreakBoardListing: () => ipcRenderer.invoke('break:copy-listing'),
  openBreakOverlay: () => ipcRenderer.invoke('break:open-overlay'),
  getOverlayStyle: () => ipcRenderer.invoke('overlay:get-style'),
  saveOverlayStyle: (style) => ipcRenderer.invoke('overlay:save-style', style),
  resetOverlayStyle: () => ipcRenderer.invoke('overlay:reset-style'),
  getConnectorStatus: () => ipcRenderer.invoke('connector:status'),
  testConnectorAssignment: (payload) => ipcRenderer.invoke('connector:test-assignment', payload),
  runConnectorStressTest: () => ipcRenderer.invoke('connector:run-stress-test'),
  resetConnectorTestAssignments: () => ipcRenderer.invoke('connector:reset-test-assignments'),
  setBuyerMessageCardMarked: (position, shouldMark) => ipcRenderer.invoke('breaker:set-message-card-marked', position, shouldMark),
  clearBuyerMessageSelections: (buyer) => ipcRenderer.invoke('breaker:clear-message-selections', buyer),
  markBuyerCardsTracked: (positions) => ipcRenderer.invoke('breaker:mark-tracker-cards', positions),
  copyBuyerCongratulations: (buyer) => ipcRenderer.invoke('breaker:copy-buyer-congratulations', buyer),
  getRiftboundChampionAudit: () => ipcRenderer.invoke('breaker:riftbound-champion-audit'),
  copyRiftboundSpotMapOverlay: () => ipcRenderer.invoke('breaker:copy-riftbound-spot-map-overlay'),
  getRiftboundSpotMapStatus: () => ipcRenderer.invoke('breaker:riftbound-spot-map-status'),
  setRiftboundSpotMapEnabled: (enabled) => ipcRenderer.invoke('breaker:set-riftbound-spot-map-enabled', { enabled }),
  copyStaticOverlay: () => ipcRenderer.invoke('breaker:copy-static-overlay'),
  getStaticOverlayStatus: () => ipcRenderer.invoke('breaker:static-overlay-status'),
  setStaticOverlayEnabled: (enabled) => ipcRenderer.invoke('breaker:set-static-overlay-enabled', { enabled }),
  setRiftboundChampionPullQuantity: (payload) => ipcRenderer.invoke('breaker:set-riftbound-champion-pull', payload),
  clearRiftboundBuyerPullSelections: (buyer) => ipcRenderer.invoke('breaker:clear-riftbound-pulls', buyer),
  copyRiftboundBuyerPulls: (buyer) => ipcRenderer.invoke('breaker:copy-riftbound-pulls', buyer),
  getPendingBreakRounds: () => ipcRenderer.invoke('break-rounds:pending'),
  finishLiveBreakRoundForReview: () => ipcRenderer.invoke('break-rounds:finish-live'),
  removePendingRoundAssignment: (payload) => ipcRenderer.invoke('break-rounds:remove-assignment', payload),
  discardPendingBreakRound: (payload) => ipcRenderer.invoke('break-rounds:discard', payload),
  setPendingRoundMessageCardMarked: (payload) => ipcRenderer.invoke('break-rounds:set-message-card', payload),
  setPendingRoundPullQuantity: (payload) => ipcRenderer.invoke('break-rounds:set-pull', payload),
  clearPendingRoundBuyerPulls: (payload) => ipcRenderer.invoke('break-rounds:clear-buyer-pulls', payload),
  copyPendingRoundBuyerPulls: (payload) => ipcRenderer.invoke('break-rounds:copy-buyer-pulls', payload),
  getPricingSettings: () => ipcRenderer.invoke('pricing:settings'),
  savePricingSettings: (payload) => ipcRenderer.invoke('pricing:save-settings', payload),
  refreshRiftboundBoardPrices: () => ipcRenderer.invoke('riftbound-board:refresh-prices'),
  prepareRiftboundBoardPriceInput: () => ipcRenderer.invoke('riftbound-board:prepare-price-input'),
  applyRiftboundBoardPriceInput: (payload) => ipcRenderer.invoke('riftbound-board:apply-price-input', payload),
  refreshLibraryListPrices: (cardIds) => ipcRenderer.invoke('library-list:refresh-prices', cardIds),
  prepareLibraryListPriceInput: (cardIds) => ipcRenderer.invoke('library-list:prepare-price-input', cardIds),
  applyLibraryListPriceInput: (payload) => ipcRenderer.invoke('library-list:apply-price-input', payload),
  refreshBuyerBagPrices: (payload) => ipcRenderer.invoke('buyer-bag:refresh-prices', payload),
  prepareBuyerBagPriceInput: (payload) => ipcRenderer.invoke('buyer-bag:prepare-price-input', payload),
  applyBuyerBagPriceInput: (payload) => ipcRenderer.invoke('buyer-bag:apply-price-input', payload),
  completeAndArchiveBreakRound: (payload) => ipcRenderer.invoke('break-rounds:complete-archive', payload),
  getPullHistory: (options) => ipcRenderer.invoke('pull-history:list', options),
  saveCurrentPullHistory: () => ipcRenderer.invoke('pull-history:save-current'),
  refreshPullHistoryPrices: (batchId) => ipcRenderer.invoke('pull-history:refresh-prices', batchId),
  preparePullHistoryPriceInput: (batchId) => ipcRenderer.invoke('pull-history:prepare-price-input', batchId),
  applyPullHistoryPriceInput: (payload) => ipcRenderer.invoke('pull-history:apply-price-input', payload),
  addPullHistoryCard: (payload) => ipcRenderer.invoke('pull-history:add-card', payload),
  deletePullHistory: (batchId) => ipcRenderer.invoke('pull-history:delete', batchId),
  getOrderHistory: (options) => ipcRenderer.invoke('history:list', options),
  saveCurrentBreakToHistory: (payload) => ipcRenderer.invoke('history:save-current-break', payload),
  updateOrderHistory: (payload) => ipcRenderer.invoke('history:update', payload),
  changeOrderTrackerDestination: (payload) => ipcRenderer.invoke('history:change-tracker-destination', payload),
  deleteOrderHistory: (id) => ipcRenderer.invoke('history:delete', id),
  getBusinessExpenses: (options) => ipcRenderer.invoke('expenses:list', options),
  saveBusinessExpense: (payload) => ipcRenderer.invoke('expenses:save', payload),
  deleteBusinessExpense: (id) => ipcRenderer.invoke('expenses:delete', id),
  getBuyerAnalytics: () => ipcRenderer.invoke('buyer-analytics:get'),
  auditBuyerPurchases: () => ipcRenderer.invoke('buyer-analytics:audit-purchases'),
  reconcileBusinessPurchases: () => ipcRenderer.invoke('business:reconcile-purchases'),
  downloadBusinessExpensePdf: (year) => ipcRenderer.invoke('business:download-pdf', year),
  downloadBusinessExpenseCsv: (year) => ipcRenderer.invoke('business:download-csv', year),
  getBuyerCaseFile: (buyer) => ipcRenderer.invoke('buyer-analytics:case-file', buyer),
  copyBuyerCaseReport: (buyer) => ipcRenderer.invoke('buyer-analytics:copy-case-report', buyer),
  getChaserTracker: () => ipcRenderer.invoke('chaser:get'), saveChaserTracker: (payload) => ipcRenderer.invoke('chaser:save', payload), setChaserCard: (id) => ipcRenderer.invoke('chaser:set-card', id), refreshChaserTracker: () => ipcRenderer.invoke('chaser:refresh'), resetChaserTracker: () => ipcRenderer.invoke('chaser:reset'), copyChaserNames: () => ipcRenderer.invoke('chaser:copy-names'), getRecentBuyerMentions: () => ipcRenderer.invoke('chaser:recent-buyers'), copyRecentBuyerMentionChunk: (index) => ipcRenderer.invoke('chaser:copy-recent-buyer-chunk', index), copyChaserOverlay: () => ipcRenderer.invoke('chaser:copy-overlay'),
  getRoyalChaserTracker: () => ipcRenderer.invoke('royal-chaser:get'), saveRoyalChaserTracker: (payload) => ipcRenderer.invoke('royal-chaser:save', payload), setRoyalChaserCard: (id) => ipcRenderer.invoke('royal-chaser:set-card', id), unlockRoyalChaserBuyer: (buyer) => ipcRenderer.invoke('royal-chaser:unlock', buyer), resetRoyalChaserTracker: () => ipcRenderer.invoke('royal-chaser:reset'), copyRoyalChaserNames: () => ipcRenderer.invoke('royal-chaser:copy-names'), copyRoyalChaserOverlay: () => ipcRenderer.invoke('royal-chaser:copy-overlay'),
  getBoxTrackers: () => ipcRenderer.invoke('box-tracker:list'),
  getOpenBoxCases: () => ipcRenderer.invoke('box-tracker:open-cases'),
  createOpenBoxCase: (payload) => ipcRenderer.invoke('box-tracker:create-open-case', payload),
  finalizeOpenBoxCase: (payload) => ipcRenderer.invoke('box-tracker:finalize-open-case', payload),
  updateOpenBoxCase: (payload) => ipcRenderer.invoke('box-tracker:update-open-case', payload),
  removeOpenBoxCaseBox: (payload) => ipcRenderer.invoke('box-tracker:remove-open-case-box', payload),
  deleteOpenBoxCase: (payload) => ipcRenderer.invoke('box-tracker:delete-open-case', payload),
  createBoxTracker: (payload) => ipcRenderer.invoke('box-tracker:create', payload),
  updateBoxTracker: (payload) => ipcRenderer.invoke('box-tracker:update', payload),
  setActiveBoxTracker: (id) => ipcRenderer.invoke('box-tracker:set-active', id),
  updateBoxTrackerBox: (payload) => ipcRenderer.invoke('box-tracker:update-box', payload),
  addBoxTrackerHitWinner: (payload) => ipcRenderer.invoke('box-tracker:add-hit-winner', payload),
  deleteBoxTrackerHitWinner: (payload) => ipcRenderer.invoke('box-tracker:delete-hit-winner', payload),
  getBoxTrackerCaseRecords: () => ipcRenderer.invoke('box-tracker:case-records'),
  saveBoxTrackerCaseRecord: (payload) => ipcRenderer.invoke('box-tracker:save-case-record', payload),
  updateBoxTrackerCaseRecord: (payload) => ipcRenderer.invoke('box-tracker:update-case-record', payload),
  deleteBoxTrackerCaseRecord: (id) => ipcRenderer.invoke('box-tracker:delete-case-record', id),
  getSalesSign: () => ipcRenderer.invoke('sales-sign:get'), saveSalesSign: (payload) => ipcRenderer.invoke('sales-sign:save', payload), copySalesSignOverlay: () => ipcRenderer.invoke('sales-sign:copy-overlay'),
  deleteBoxTracker: (id) => ipcRenderer.invoke('box-tracker:delete', id),
  copyBoxTrackerOverlayLink: () => ipcRenderer.invoke('box-tracker:copy-overlay-link'),
  copyBoxTrackerTitleOverlayLink: () => ipcRenderer.invoke('box-tracker:copy-title-overlay-link'),
  copyBoxTrackerHitsOverlayLink: () => ipcRenderer.invoke('box-tracker:copy-hits-overlay-link'),
  openBoxTrackerOverlay: () => ipcRenderer.invoke('box-tracker:open-overlay'),
  copyActiveCaseOverlayLink: () => ipcRenderer.invoke('box-tracker:copy-active-case-overlay-link'),
  openActiveCaseOverlay: () => ipcRenderer.invoke('box-tracker:open-active-case-overlay'),
  onBreakBoardChanged: (callback) => {
    const listener = (_event, cards) => callback(cards);
    ipcRenderer.on('break:board-changed', listener);
    return () => ipcRenderer.removeListener('break:board-changed', listener);
  },
  onConnectorStatusChanged: (callback) => {
    const listener = (_event, status) => callback(status);
    ipcRenderer.on('connector:status-changed', listener);
    return () => ipcRenderer.removeListener('connector:status-changed', listener);
  },
  repairLibrary: () => ipcRenderer.invoke('library:repair'),
  onDonCatalogSyncComplete: (callback) => {
    const listener = (_event, result) => callback(result);
    ipcRenderer.on('library:don-sync-complete', listener);
    return () => ipcRenderer.removeListener('library:don-sync-complete', listener);
  },
  resetLibrary: (confirmation) => ipcRenderer.invoke('library:reset', confirmation),
  importOfficialCards: () => ipcRenderer.invoke('import:run-official'),
  getRiftboundApiStatus: () => ipcRenderer.invoke('import:riftbound-api-status'),
  saveRiftboundApiKey: (apiKey) => ipcRenderer.invoke('import:save-riftbound-api-key', apiKey),
  importOfficialRiftboundCards: () => ipcRenderer.invoke('import:run-riftbound-official'),
  refreshOpenRiftImages: () => ipcRenderer.invoke('import:refresh-openrift-images'),
  importRiftboundJson: () => ipcRenderer.invoke('import:riftbound-json'),
  getLastImport: () => ipcRenderer.invoke('import:last-session'),
  onImportProgress: (callback) => {
    const listener = (_event, progress) => callback(progress);
    ipcRenderer.on('import:progress', listener);
    return () => ipcRenderer.removeListener('import:progress', listener);
  },
  onRiftboundImportProgress: (callback) => {
    const listener = (_event, progress) => callback(progress);
    ipcRenderer.on('riftbound:import-progress', listener);
    return () => ipcRenderer.removeListener('riftbound:import-progress', listener);
  },
  getCardSniperStatus: () => ipcRenderer.invoke('sniper:status'),
  saveCardSniperSettings: (settings) => ipcRenderer.invoke('sniper:save-settings', settings),
  getCardSniperSets: () => ipcRenderer.invoke('sniper:sets'),
  getCardSniperLatest: (setCode) => ipcRenderer.invoke('sniper:latest', setCode),
  scanCardSniperSet: (setCode) => ipcRenderer.invoke('sniper:scan-set', setCode),
  getPlayableMarketSets: () => ipcRenderer.invoke('playable-market:sets'),
  getPlayableMarketDashboard: (options) => ipcRenderer.invoke('playable-market:dashboard', options),
  preparePlayableMarketResearch: (setCode) => ipcRenderer.invoke('playable-market:prepare-research', setCode),
  applyPlayableMarketResearch: (payload) => ipcRenderer.invoke('playable-market:apply-research', payload),
  removePlayableMarketCard: (cardId) => ipcRenderer.invoke('playable-market:remove-card', cardId),
  getDatabaseStatus: () => ipcRenderer.invoke('app:database-status'),
  openExternal: (url) => ipcRenderer.invoke('app:open-external', url),
  pin: {
    getSettings: () => ipcRenderer.invoke('pin:get-settings'),
    saveSettings: (settings) => ipcRenderer.invoke('pin:save-settings', settings),
    testConnection: () => ipcRenderer.invoke('pin:test-connection'),
    sendPing: (message) => ipcRenderer.invoke('pin:send-ping', message),
    setLive: (live) => ipcRenderer.invoke('pin:set-live', live)
  }
});
